{% set name = "gtdbtk" %}
{% set version = "0.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/Ecogenomics/GTDBTk/archive/{{ version }}.tar.gz
  sha256: cae0987c1ddb8e1e98e2417c1845785d84c210b23c05eb2bbe75399c63f2eb7a
  patches:
    - config_file.patch
    - main.patch

build:
  number: 1
  skip: True  # [py3k or osx]

requirements:
  host:
    - biolib >=0.0.43
    - dendropy >=4.1.0
    - jinja2 >=2.7.3
    - mpld3 >=0.2
    - pip
    - python
    - scipy
    - perl-gtdbtk
  run:
    - biolib >=0.0.43
    - dendropy >=4.1.0
    - jinja2 >=2.7.3
    - mpld3 >=0.2
    - python
    - scipy
    - prodigal
    - hmmer
    - pplacer
    - fastani
    - fasttree
    - perl-gtdbtk

test:
  commands:
    - export GTDBTK_DB_PATH=${PREFIX}/share/${PKG_NAME}-${PKG_VERSION}/db && gtdbtk -h
  imports:
    - gtdbtk
    - gtdbtk.config
    - gtdbtk.external

about:
  home: http://pypi.python.org/pypi/gtdbtk/
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A toolkit for assigning objective taxonomic classifications to bacterial and archaeal genomes.'

extra:
  skip-lints:
    - should_be_noarch_python
    - should_not_use_skip_python
